
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: travis
    password:
    url: jdbc:mysql://127.0.0.1/e2x?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
jpa:
  show-sql: true

server:
  servlet:
    context-path: /api
  port: 8080

# password salt
jasypt:
  encryptor:
    password: iwork@dataseek